### ISSUE TITLE
Unable to setup timesaver plugin

### ISSUE THREAD

**Issue by Alok650** [tduniec/backstage-timesaver-plugin#2]
**Issue:**
I have configured time saver plugin - frontend & backend
However, on <URL>/time-saver, I am getting 404 for all the time-saver endpoint. In my Postgres, DB for this plugin is not getting created.

**Ref. image**
<img width="1490" alt="image" src="https://github.com/tduniec/backstage-timesaver-plugin/assets/58817460/e919897e-5103-41d7-98e0-ce3177fb8a8f">

Added in template.yaml:
`metadata:
    substitute:
      engineering:
        sre: 1
        security: 1
        development_teams: 2`

**Comment by tduniec** [comment]
Hey,

thank you for interest in plugin. 

can you confirm the migration file was executed on your backend init ? 
can you see database or schema ? 

What kind of error you are getting. Seems like the plugin is not available on backend. 

Please tell me the output of:
Localhost:7007/api/time-saver/health

**Comment by Alok650** [comment]
The above was fixed. Issue was with the backend plugin setup (package version mismatch).

Another issue:
In my template.yaml, I have written time-saved ie.

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-service-onboarding
  title: New Service Onboarding
  description: Onboards a new microservice
  substitute:
    engineering:
     develops: 1
      security: 1
      development_teams: 2
```

but currently its not getting ingested into the time-saver plugin (don't see any change in UI).


Questions:
1. is substitute necessary in the yaml?
2. How does the ingestion for these metrics happen? is it a push based mech. where every time some triggers a execution, it will push metrics from that template into time-saver db. or is it based on polling (if so, can I configure at what interval the pull from /create/tasks would happen)
3. Do the groups defined in the template yaml need to be ingested as group entities in the catalog?
