### ISSUE TITLE
401 Unauthorized Issue

### ISSUE THREAD

**Issue by Longji-Kang** [tduniec/backstage-timesaver-plugin#3]
# The Issue
We are trying to setup the timesaver plugin on our backstage instance and are running into a bit of a weird issue. The dashboard for time saver is running into 401 Unauthorized errors. 

![image](https://github.com/tduniec/backstage-timesaver-plugin/assets/91741938/7c02883b-e565-401d-8a22-c4d1660ba934)

We have setup the permissions in the permissions plugin to just return AuthorizeResult.Allow for timeSaverPermission.

**Comment by toma2395** [comment]
Hey, 

thank you for rising the issue. Let's check out your case. 
Probably you backend is being protected with Authorization header, which is not recognized by time-saver plugin. If you have protected backend time-saver is using first secret under auth config. 

```
  # See https://backstage.io/docs/auth/service-to-service-auth for
  auth:
    keys:
      - secret: 'secretValue' 
```

Can we connect for debugging session?
